name: environment_hackaton
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  audioplayers: ^5.2.1
  bloc: ^8.1.3
  equatable: ^2.0.5
  flame: ^1.16.0
  flame_audio: ^2.1.8
  flame_bloc: ^1.10.10
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.1.0
  intl: ^0.18.1
  path_provider: ^2.1.2

dev_dependencies:
  bloc_test: ^9.1.6
  build_runner: ^2.4.8
  flame_lint: ^1.1.2
  flame_test: ^1.15.4
  flutter_gen_runner: ^5.4.0
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  mockingjay: ^0.5.0
  mocktail: ^1.0.3
  path_provider_android: ^2.2.2
  very_good_analysis: ^5.1.0

scripts: derry.yaml

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/audio/
    - assets/images/
    - assets/licenses/poppins/
