name: environment_hackaton
description: A Very Good Project created by Very Good CLI.
version: 1.0.1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  animated_button: ^0.3.1
  app_ui:
    path: packages/app_ui
  audioplayers: ^6.6.0
  bloc: ^9.2.0
  copy_with_extension: ^15.0.0
  equatable: ^2.0.5
  equatable_annotations: ^1.2.0
  flame: ^1.16.0
  flame_audio: ^2.1.8
  flame_behaviors: ^1.1.0
  flame_bloc: ^1.10.10
  flame_splash_screen: ^0.3.1+2
  flame_tiled: ^3.0.11

  flutter:
    sdk: flutter

  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_shaders: ^0.1.2
  flutter_svg: ^2.0.10+1
  google_fonts: ^8.1.0
  intl: ^0.20.2
  path_provider: ^2.1.2
  sip_cli: ^0.18.7

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.8
  copy_with_extension_gen: ^15.0.0
  equatable_gen: ^1.3.2
  flame_lint: ^1.1.2
  flame_test: ^2.2.2
  flutter_gen_runner: ^5.4.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0

scripts: derry.yaml

# fonts:
#   - family: PublicPixel
#     fonts:
#       - asset: assets/fonts/PublicPixel-z84yD.ttf
#   - family: Pixelify
#     fonts:
#       - asset: assets/fonts/Pixelify_Sans/PixelifySans-VariableFont_wght.ttf

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/audio/
    - assets/images/
    - assets/images/player/
    - assets/images/parallax/
    - assets/images/hud/
    - assets/images/overlay/
    - assets/images/interactables/
    - assets/tiles/
    - assets/images/player/json/

  shaders:
    - assets/shaders/darkening_shader.frag
